### ISSUE TITLE
Images with Duplicate Names

### ISSUE THREAD

**Issue by Plinpod** [keeross/DigitalOcean-Spaces-Sync#22]
Hello,

There seems to be an issue with images that are uploaded with duplicate filenames. The script doesn't append any characters to the new file and the old files just stays on the server. So the duplicate filename in the media library just shows the original image.

Has anyone ran into this? Thanks!

**Comment by keeross** [comment]
Not sure about your problem, have just tested, works fine. Could you please update plugin to the latest version.

**Comment by tansautn** [comment]
@keeross On my website. this issue will occur when the option below is enabled
![chrome_2019-08-08_13-53-30](https://user-images.githubusercontent.com/6666271/62682147-a0ec4980-b9e5-11e9-9f18-4c7f0f9c300e.png)

As I understand, the script performs upload to DO cdn after the WP has finished uploading the file to the WP server. and after uploading to CDN successfully, immediately delete the file on WP server.

When uploading the next file with the same name, because the previous file was deleted on the WP server, appending number to file name is unnecessary.

**Comment by tansautn** [comment]
the main problem is : storage_prefix was not added to check exists file name on CDN

https://github.com/keeross/DigitalOcean-Spaces-Sync/blob/0052d749b142b278f12d51c81c74a0265745ebce/dos_class.php#L187

**Comment by opicron** [comment]
Will this be merged any time soon?
